// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttkbtoxcmbshcqfpcike.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0a2J0b3hjbWJzaGNxZnBjaWtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MDc5NTgsImV4cCI6MjA2MjA4Mzk1OH0.s9Lndy_xGVe4kl0NdUGFx2qmqINr-dJD7i7ItF-yqS0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);